insert into api.love_quotes(quote) values ('你知道我喜欢谁吗，不知道就看看第一个字。');
insert into api.love_quotes(quote) values ('我有超能力，超喜欢你。');
insert into api.love_quotes(quote) values ('我喜欢夏天的雨，雨后的光，和任何时候的你');
insert into api.love_quotes(quote) values ('“做我女朋友行不行?不行我再想想办法。”“你的口红我包了，但以后记得每天还我一点点。”');
insert into api.love_quotes(quote) values ('我路过很多很美的风景，最后却只想在你这里停留。');
insert into api.love_quotes(quote) values ('我的手被划了一道口子 你也划一下 这样我们就是两口子了。');
insert into api.love_quotes(quote) values ('“请管好你的嘴。”“为什么?”“因为我随时会亲它。”');
insert into api.love_quotes(quote) values ('最近有谣言说我喜欢你，我要澄清一下，那不是谣言');
insert into api.love_quotes(quote) values ('“你猜我想吃什么?” “不知道啊。” “痴痴地望着你。”');
insert into api.love_quotes(quote) values ('“我觉得你这个人不适合谈恋爱。”“为什么?”“适合结婚。”');
insert into api.love_quotes(quote) values ('人生呐，最美好的两件事，就是睡你——睡觉，和你');
insert into api.love_quotes(quote) values ('“甜有100钟方式，你知道吗？” “不知道” “吃糖，蛋糕，还有每天98次的想你。”');
insert into api.love_quotes(quote) values ('好好照顾自己，不行就让我来照顾你');
insert into api.love_quotes(quote) values ('我还是喜欢你，像小时候吃辣条，从不看日期');
insert into api.love_quotes(quote) values ('给你的表白话是抄的，但是我对你的爱是24K纯真的。');
insert into api.love_quotes(quote) values ('别人再好都是别人的，我不一样，我是你的');
insert into api.love_quotes(quote) values ('我有笔好几亿的生意，想和你谈谈');
insert into api.love_quotes(quote) values ('你上辈子一定是碳酸饮料吧，为什么我一看到你就能开心的冒泡。');
insert into api.love_quotes(quote) values ('喜欢你已经超过两分钟，不能撤回了');
insert into api.love_quotes(quote) values ('我想你一定很忙，所以只看前三个字就好啦');
insert into api.love_quotes(quote) values ('“你有男朋友吗”“没有”“那恭喜你，现在有了。”');
insert into api.love_quotes(quote) values ('我想和你一房二人三餐四季。');
insert into api.love_quotes(quote) values ('答案很长，我准备用一生的时间来回答，你准备要听了吗？');
insert into api.love_quotes(quote) values ('你今天特别讨厌，讨人喜欢和百看不厌。');
insert into api.love_quotes(quote) values ('听闻先生治家有方，小女余生愿闻其详');
insert into api.love_quotes(quote) values ('何以解忧，唯有暴… ?嗯? …抱抱你');
insert into api.love_quotes(quote) values ('“你知道世界上最冷的地方是哪吗?”“是没有你的地方”。');
insert into api.love_quotes(quote) values ('天再冷只要感受到你掌心里的温度就好。');
insert into api.love_quotes(quote) values ('“天气这么冷，你知道怎么取暖吗？”“不知道。”“我也不知道，但我知道怎么娶你。”');
insert into api.love_quotes(quote) values ('对你，我已经无条件投降了');
insert into api.love_quotes(quote) values ('陪迩去看细水长流');
insert into api.love_quotes(quote) values ('你的过去我没来得及参与，但是你的未来我一定至死不渝。');
insert into api.love_quotes(quote) values ('从今以后我只能称呼你为您了，因为，你在我心上。');
insert into api.love_quotes(quote) values ('“嘿，我想像一首歌给你听” “什么歌?” “打呼噜”');
insert into api.love_quotes(quote) values ('希望有一天，你来到这个城市，是因为想起了我');
insert into api.love_quotes(quote) values ('你有没有闻到烧焦的味道 ！那是我的心在燃烧');
insert into api.love_quotes(quote) values ('你是我最初也是最后爱的人。');
insert into api.love_quotes(quote) values ('你和所有的前任比起来，他们不过是前戏，你才是我想要的高潮');
insert into api.love_quotes(quote) values ('你生是我的猪，死是我的五花肉');
insert into api.love_quotes(quote) values ('你知道我的缺点是什么吗? 是缺点你。');
insert into api.love_quotes(quote) values ('“我想买一块地。”“什么地?”“你的死心塌地。”');
insert into api.love_quotes(quote) values ('我在找一匹马。什么马?你的微信号码。');
insert into api.love_quotes(quote) values ('“我掐指一算，你五行缺我。”“我是迷人的男人，你是迷人。”');
insert into api.love_quotes(quote) values ('你长得很像我一个亲戚，我妈的女婿。');
insert into api.love_quotes(quote) values ('无事献殷勤，非  非常喜欢你。会当凌绝顶，一');
insert into api.love_quotes(quote) values ('“你知道现在几点吗?”“六点。”“不，是我们幸福的起点。”');
insert into api.love_quotes(quote) values ('我想你看看我的眼睛，其实我的眼里，只有你。');
insert into api.love_quotes(quote) values ('我的爱情在你这里，永远不会离去');
insert into api.love_quotes(quote) values ('你知道你和星星有什么区别吗?星星在天上，你在我心里。');
insert into api.love_quotes(quote) values ('“你为什么要害我?”“害你什么?”“害我那么喜欢你!”');
insert into api.love_quotes(quote) values ('“你知道你现在像什么吗?”“像什么?”“像地球。”“为什么?”“因为你对我有吸引力。”');
insert into api.love_quotes(quote) values ('你说「好想有个完全属于自己的空间啊！」却没注意到我早已为你腾空心房，面积虽小，冷暖可调，租期你定，眼神解锁，费用「一次心动」，欢迎拎包入住。');
insert into api.love_quotes(quote) values ('你可以笑一下吗？我的咖啡没加糖');
insert into api.love_quotes(quote) values ('你眼瞎吗?撞我心口上了。');
insert into api.love_quotes(quote) values ('不管今世也来世也好，我所要的只有你。');
insert into api.love_quotes(quote) values ('“我想在你那里买一块地。”“买什么地?”“买你的死心塌地。”');
insert into api.love_quotes(quote) values ('“游乐园那个，可以骑在上面的”“有音乐的叫旋转什么?”“木马。”“mua”');
insert into api.love_quotes(quote) values ('“我喜欢上一个小哥哥。”“那他一定很帅。”“你太自恋了。”');
insert into api.love_quotes(quote) values ('你是水，我是鱼，相伴相知。');
insert into api.love_quotes(quote) values ('你无需开口，我和天地万物便通通奔向你。');
insert into api.love_quotes(quote) values ('我对你的爱，就像拖拉机上山，轰轰烈烈……');
insert into api.love_quotes(quote) values ('我对你的爱很宽，愿你在我的爱里，一生都迷路。');
insert into api.love_quotes(quote) values ('我能陪你熬夜也会劝你早睡。');
insert into api.love_quotes(quote) values ('我对你的喜欢可以绕地球很多很多圈');
insert into api.love_quotes(quote) values ('用情，去珍惜你一生。');
insert into api.love_quotes(quote) values ('“妈我爱你，倒过来怎么说?”“你爱我吗”“爱。”');
insert into api.love_quotes(quote) values ('脑子真神奇，忙的要死，也要留个小缝儿想你');
insert into api.love_quotes(quote) values ('“你好宅啊。”“没有啊。”“可你呆在我的心里就没动过。”');
insert into api.love_quotes(quote) values ('我喜欢你这件事，太直接了，没办法拐弯。');
insert into api.love_quotes(quote) values ('冬天到了喝点什么，不知道 呵护你');
insert into api.love_quotes(quote) values ('“我这么胖，你为什么还这么喜欢我”“你瘦的时候进我心里，胖的时候就卡住了，出不来了”');
insert into api.love_quotes(quote) values ('我不需要什么奇迹奇迹，我现在就需要你。');
insert into api.love_quotes(quote) values ('“你知道你和星星有什么区别吗?”“有什么区别”“星星在天上，而你在我心里。”');
insert into api.love_quotes(quote) values ('我喜欢你，心就特别软，平淡也浪漫，无语也温暖。');
insert into api.love_quotes(quote) values ('你近视吗?(不近视啊)那你怎么看不出我喜欢你。');
insert into api.love_quotes(quote) values ('我知道没有能让你一见钟情的脸，但是很多事靠感觉不是吗。');
insert into api.love_quotes(quote) values ('“你累不累啊?”“不累。”“可是你都在我脑里跑了一天了！”');
insert into api.love_quotes(quote) values ('你不爱我又如何，我爱你就够了。');
insert into api.love_quotes(quote) values ('你是我最爱的女孩，再多奶茶都不换那种。');
insert into api.love_quotes(quote) values ('“喂，知道风灌进胸膛是什么感觉么”“不知道啊”“就知道不知道，因为进入的人是你啊。”');
insert into api.love_quotes(quote) values ('可爱不是长久之计，可爱我是长久之计');
insert into api.love_quotes(quote) values ('我就是喜欢你，怎样了。');
insert into api.love_quotes(quote) values ('客户虐我千百遍，我待客户如初恋，还不是因为客户是你');
insert into api.love_quotes(quote) values ('“你最近是不是又胖了?” “没有啊，为什么这么说?” “那为什么在我心里的分量越来越重了?”');
insert into api.love_quotes(quote) values ('“我背你好吗？”“');
insert into api.love_quotes(quote) values ('立刻有=like you');
insert into api.love_quotes(quote) values ('你是别人眼中的小恶魔，却是我心中的大天使。');
insert into api.love_quotes(quote) values ('遇见你之后，灵魂不再孤独');
insert into api.love_quotes(quote) values ('除了你，我没人要。除了你，我谁都不要。');
insert into api.love_quotes(quote) values ('我觉得你好像一款游戏。什么游戏?我的世界。');
insert into api.love_quotes(quote) values ('我想去取一下东西，你等一下，我来娶你了。');
insert into api.love_quotes(quote) values ('“这辈子就跟我在一起吧，不行的话我再等等，还不行的话我再想想别的办法。”');
insert into api.love_quotes(quote) values ('说简单点是熬夜，说实在点是失眠，说具体的是想你。');
insert into api.love_quotes(quote) values ('如果爱不疯狂就不是爱了。');
insert into api.love_quotes(quote) values ('这是我的手背，这是我的脚背，你是我的宝贝。');
insert into api.love_quotes(quote) values ('别嫌弃我什么都不会，但是我只会娶你。');
insert into api.love_quotes(quote) values ('“我结婚你一定要来”“为什么？”“因为没有新娘会很尴尬。”');
insert into api.love_quotes(quote) values ('你知道这道菜怎么吃最好吃吗? 趁热吗? 我喂你吃。');
insert into api.love_quotes(quote) values ('有机会把耳机分你一个，然后开启网易云的心动模式。');
insert into api.love_quotes(quote) values ('我生在南方，活在南方，栽在你手里，总算是去过不一样的地方。');
insert into api.love_quotes(quote) values ('你猜我什么座？我是为你量身定做');
insert into api.love_quotes(quote) values ('你是我唯一，我是你什么。');
insert into api.love_quotes(quote) values ('游乐场那个旋转的，有音乐会转的是什么？木马？嗯，mua');
insert into api.love_quotes(quote) values ('自从爱你以后，才知爱的甜美。');
insert into api.love_quotes(quote) values ('有你在的地方，天气明朗，万物可爱。');
insert into api.love_quotes(quote) values ('“我重要吗？”“再重都要”');
insert into api.love_quotes(quote) values ('今年的冬天，我可不可以拥抱你');
insert into api.love_quotes(quote) values ('我还是喜欢你，像小时候吃辣条，不看日期。');
insert into api.love_quotes(quote) values ('你是我的唯一。');
insert into api.love_quotes(quote) values ('我不想做好人或坏人，只想做你心上人。');
insert into api.love_quotes(quote) values ('你笑的时候我就好像拥有了全世界。');
insert into api.love_quotes(quote) values ('你有没有问到什么烧焦的味道?那是我的心在燃烧。');
insert into api.love_quotes(quote) values ('你给我的爱在心窝窝。');
insert into api.love_quotes(quote) values ('我是九你是三，除了你还是你');
insert into api.love_quotes(quote) values ('“帮我看看我眼睛怎么了?”“没看到有什么啊”“没吗?再仔细找找”“真的没有”“有，我的眼睛里有你啊”');
insert into api.love_quotes(quote) values ('因为我爱你，所以纵容你。');
insert into api.love_quotes(quote) values ('我给你备注为一行…因为干一行，爱一行');
insert into api.love_quotes(quote) values ('“你猜我什么星座” “白羊?” “错，我是为你量身定做”');
insert into api.love_quotes(quote) values ('“我怀疑你是碳酸饮料。”“为什么?”“因为一遇见你，我就开心地冒泡泡。”');
insert into api.love_quotes(quote) values ('我会永远永远记住你给的浪漫惊喜。');
insert into api.love_quotes(quote) values ('你闻到什么味道了吗?没有啊！怎么你一出来空气都是甜的了。');
insert into api.love_quotes(quote) values ('跟着我，别走丢。');
insert into api.love_quotes(quote) values ('风止于秋水，我止于你');
insert into api.love_quotes(quote) values ('没有你，就像热干面没有芝麻酱，毫无滋味');
insert into api.love_quotes(quote) values ('“你左手有几个手指”“5”“你有几个眼睛”“2”“你有几个嘴巴”“1”“嗯 我也爱你”');
insert into api.love_quotes(quote) values ('我房租到期了，可以去你心里住吗');
insert into api.love_quotes(quote) values ('“孔子 孟子 老子，你知道你最适合当什么子吗?”“不知道。”“我的妻子。”');
insert into api.love_quotes(quote) values ('番茄和西红柿，土豆和马铃薯，我喜欢的人和你');
insert into api.love_quotes(quote) values ('来者何人？你的人');
insert into api.love_quotes(quote) values ('“要是我和你生一个孩子你觉得他会是什么座？”“什么座？双子座？”“不，我们的杰作。”');
insert into api.love_quotes(quote) values ('你出现的那一刻起	就是我全部的风景-');
insert into api.love_quotes(quote) values ('情话都是学来的，但爱你是真的');
insert into api.love_quotes(quote) values ('最近有谣言说我喜欢你，我要澄清一下那不是谣言');
insert into api.love_quotes(quote) values ('你可以帮我个忙么? 什么忙? 帮忙快点爱上我!');
insert into api.love_quotes(quote) values ('喜欢上你不在我的计划之中，只是刚好发生。');
insert into api.love_quotes(quote) values ('我们，是我遇见的最美好的字眼');
insert into api.love_quotes(quote) values ('关关雎鸠，在河之洲，窈窕淑女，what*s you qq？');
insert into api.love_quotes(quote) values ('“你永远也看不到我寂寞的样子”“为什么了”“因为只有你不在我身边的时候，我才是最寂寞的”');
insert into api.love_quotes(quote) values ('眼里都是你，亿万星辰犹不及');
insert into api.love_quotes(quote) values ('你最近是不是又胖了？那为什么在我心里份量越来越重了？');
insert into api.love_quotes(quote) values ('想送你很多很多口红，让你每天还我一点点');
insert into api.love_quotes(quote) values ('你要你在我身边，我会爱你爱的无法无天。');
insert into api.love_quotes(quote) values ('东风夜放花千树，我想去你家里住');
insert into api.love_quotes(quote) values ('你知道我喜欢喝什么吗？ 呵护你');
insert into api.love_quotes(quote) values ('你从一个陌生人，变成了我最不舍的离开的人。');
insert into api.love_quotes(quote) values ('“我好像找不到方向了”“你要去哪里”“通往你的心里，该怎么走?”');
insert into api.love_quotes(quote) values ('你是我一生中上天最唯美的安排');
insert into api.love_quotes(quote) values ('我的眼睛一定有问题，我的视线无法自你身上离开。');
insert into api.love_quotes(quote) values ('近朱者赤，近你者甜。');
insert into api.love_quotes(quote) values ('你会弹吉他吗 不会 那你为什么能拨动我的心弦');
insert into api.love_quotes(quote) values ('“我饮料都喝无糖的，你知道你适合和什么糖的么?” “微糖吧” “不对，是我的胸膛”');
insert into api.love_quotes(quote) values ('我想在老的时候，吻你光光的牙床');
insert into api.love_quotes(quote) values ('你是甜筒吗？为什么我想舔遍你全身');
insert into api.love_quotes(quote) values ('我的身体24小时都营业，只等待你的进入');
insert into api.love_quotes(quote) values ('“你能不能闭嘴?”“我没有说话啊”“那为什么我满脑子都是你的声音?”');
insert into api.love_quotes(quote) values ('我骄傲了十几年看见你我就怂了。');
insert into api.love_quotes(quote) values ('你上辈子一定是碳酸饮料吧，为什么我一看到你就能开心的冒泡？');
insert into api.love_quotes(quote) values ('玫瑰是我偷的，但我爱你是真的。');
insert into api.love_quotes(quote) values ('您好，您有新的恋爱订单，请及时收取我');
insert into api.love_quotes(quote) values ('你问我多喜欢你，我说不出来。但是我心里明白，我宁愿和你吵架，也不愿意去爱别人');
insert into api.love_quotes(quote) values ('无论你在哪，我的心永远追随着你');
insert into api.love_quotes(quote) values ('你的脸上有点东西，有什么?有点漂亮。');
insert into api.love_quotes(quote) values ('情人眼里出什么？西施？不，是出现你。');
insert into api.love_quotes(quote) values ('“我们现在是朋友吗?”“是啊”“那以后就不是了，因为你是我女朋友”;');
insert into api.love_quotes(quote) values ('我的爱情一生只有一次，一次就是一生！');
insert into api.love_quotes(quote) values ('“你是什么血型？” “A型啊！” “不，你是我的理想型！”');
insert into api.love_quotes(quote) values ('只许州官放火，不许你离开我。');
insert into api.love_quotes(quote) values ('我可以不为别人难过，但你不是别人，你是我的人。');
insert into api.love_quotes(quote) values ('你把你的缺点给我我来包容你');
insert into api.love_quotes(quote) values ('我怀疑你的本质是一本书，不然为什么让我越看越想睡。');
insert into api.love_quotes(quote) values ('不要抱怨，抱我。');
insert into api.love_quotes(quote) values ('余生很长，想和你没完没了');
insert into api.love_quotes(quote) values ('“你是心你是肝你是我的四分之三”');
insert into api.love_quotes(quote) values ('你猜我爱喝酒还是爱打王者 爱打王者吧? 不，爱你');
insert into api.love_quotes(quote) values ('每天只想和你做四件事——一日三餐');
insert into api.love_quotes(quote) values ('我能对你说上一世情话不带重样的。');
insert into api.love_quotes(quote) values ('你知道现在是几点嘛？是我们幸福的起点');
insert into api.love_quotes(quote) values ('你陪我走过一无所有，我陪你走到岁月尽头。');
insert into api.love_quotes(quote) values ('你开心吗？开啊，不开你怎么进来');
insert into api.love_quotes(quote) values ('你知道吗？咋两都挺过分的，你过分美丽，我过分着迷');
insert into api.love_quotes(quote) values ('你上辈子一定是碳酸饮料吧，为什么我一看到你就开心的冒泡');
insert into api.love_quotes(quote) values ('和你聊天就像考试，事后想想总是觉没有发挥好。');
insert into api.love_quotes(quote) values ('我喜欢你，你喜欢我吗？不喜欢的话，我再想想办法。');
insert into api.love_quotes(quote) values ('说不过你但喜欢你。');
insert into api.love_quotes(quote) values ('你不要仗着我爱你，你就刻意为所欲为。');
insert into api.love_quotes(quote) values ('我以为我过得还挺好的，吃得饱，穿的好，有钱花。只是还差一点什么，还差一个你');
insert into api.love_quotes(quote) values ('我与世界只差一个你，因为是你，晚一点没关系。');
insert into api.love_quotes(quote) values ('你知不知道为什么我怕你？”“不知道”“因为我怕老婆');
insert into api.love_quotes(quote) values ('“别人都说你的脸很圆，但我觉得你的脸还蛮方的” “为什么?” “不然怎么那么正”');
insert into api.love_quotes(quote) values ('我们来玩木头人不许动吧 好!我输了，心动了。');
insert into api.love_quotes(quote) values ('很感谢在最美的时光遇见最美的你。');
insert into api.love_quotes(quote) values ('随时都想吻你，也很想听你的心跳。');
insert into api.love_quotes(quote) values ('你若一直在我便一直爱');
insert into api.love_quotes(quote) values ('“咱俩友情到头了，该发展成爱情了。”“别人是喜欢你，而我是只喜欢你。”“我可以称呼你为您吗?这样我就可以把你放在心上。”');
insert into api.love_quotes(quote) values ('“你可以笑一个吗?”“为什么啊?”“因为我的咖啡忘加糖了。”');
insert into api.love_quotes(quote) values ('全世界还有谁比我们更般配。');
insert into api.love_quotes(quote) values ('我努力不是为了你而是因为你。');
insert into api.love_quotes(quote) values ('传闻人有206根骨头，一遇见你呀，我就有207根啦');
insert into api.love_quotes(quote) values ('我这个人没见过什么世面，见见你就已经足够了。');
insert into api.love_quotes(quote) values ('对你这种人，除了恋爱，我没什么和你谈的！');
insert into api.love_quotes(quote) values ('我最美的年华，不是你，而是爱你的年华里那些甜蜜的小心情。');
insert into api.love_quotes(quote) values ('“你是哪里人” “杭州人” “不，你是我的心上人。”');
insert into api.love_quotes(quote) values ('前半生到处浪荡，后半生为你煲汤。');
insert into api.love_quotes(quote) values ('一直想说，无论走到哪里，最想去的是你的身边。');
insert into api.love_quotes(quote) values ('既然你已经把我的心弄乱了，那么你准备什么时候来弄乱我的床');
insert into api.love_quotes(quote) values ('有一天我会拉着你的手，带你去看你最喜欢的星空。');
insert into api.love_quotes(quote) values ('你最可爱了。我说的时候来不及思索，我仔细想过之后，还是会这么说');
insert into api.love_quotes(quote) values ('莫文蔚的阴天，孙燕姿的雨天，周杰伦的晴天，都不如你和我聊天。');
insert into api.love_quotes(quote) values ('我身体很好，可以扛米袋子，抗煤气罐，就是扛不住想你');
insert into api.love_quotes(quote) values ('把你的名字写在烟上吸进肺里，让你保持在离我心脏最近的地方。');
insert into api.love_quotes(quote) values ('有趣的地方都想去掺和一下，比如你的世界');
insert into api.love_quotes(quote) values ('野心不大，有你就拥有天下！');
insert into api.love_quotes(quote) values ('我喜欢你，喜欢得无可救药。');
insert into api.love_quotes(quote) values ('“你觉得你适合穿什么衣服？”“好看的衣服？”“不，是被我征服。”');
insert into api.love_quotes(quote) values ('“孔子 孟子 老子，你知道你最适合当什么子吗？”“不知道。”“我的妻子。”');
insert into api.love_quotes(quote) values ('你今天干嘛打扮成这个样子，好看不说，偏偏是我喜欢的样子');
insert into api.love_quotes(quote) values ('但愿我和你，是一支唱不完的歌。');
insert into api.love_quotes(quote) values ('你的眼睛真漂亮里面只适合装我');
insert into api.love_quotes(quote) values ('现在几点了?(12点)不，是我们幸福的起点。');
insert into api.love_quotes(quote) values ('“最近我看到你就觉得头很晕”“为什么?”“因为爱情使人头昏脑胀”');
insert into api.love_quotes(quote) values ('“你可以做我的奥利奥吗？”“为什么？”“因为我想泡你。”');
insert into api.love_quotes(quote) values ('此刻我很挂念你，请为我小心照顾自己。');
insert into api.love_quotes(quote) values ('“我觉得你长得像我一个亲戚。”“谁？”“我妈的儿媳妇。”');
insert into api.love_quotes(quote) values ('你喜欢喝水吗?那你已经喜欢上70%的我了。');
insert into api.love_quotes(quote) values ('你知道你和星星的区别吗？星星在天上 你在我心里');
insert into api.love_quotes(quote) values ('“你知道这牛肉要怎么吃才好吃吗？我喂你吃。”');
insert into api.love_quotes(quote) values ('爱你在我心窝窝里~');
insert into api.love_quotes(quote) values ('你的酒窝没有酒，我却醉的像条狗');
insert into api.love_quotes(quote) values ('等下可以帮我洗一下东西吗？”“可以啊，洗什么？”“喜欢我。”');
insert into api.love_quotes(quote) values ('我最大的缺点，就是缺点你');
insert into api.love_quotes(quote) values ('春雨初生，春树初盛，春风十里，不如你。');
insert into api.love_quotes(quote) values ('我的心脏只够装下你');
insert into api.love_quotes(quote) values ('今天我想你想的，连续换了五条小内裤');
insert into api.love_quotes(quote) values ('我很能干但有一件事不会。什么?不会离开你。');
insert into api.love_quotes(quote) values ('天冷了 有什么事 到我被窝里说。');
insert into api.love_quotes(quote) values ('我没什么事儿，就想听听你的声音。');
insert into api.love_quotes(quote) values ('因为你，我懂得了爱。');
insert into api.love_quotes(quote) values ('“我感觉地震了，怎么老是在动。” “没有啊” “');
insert into api.love_quotes(quote) values ('被你赞过的朋友圈，叫甜甜圈。');
insert into api.love_quotes(quote) values ('“你属什么？”“我属狗。”“你不要再骗人了，你属于我。”');
insert into api.love_quotes(quote) values ('我愿意做你最温馨的避风港。');
insert into api.love_quotes(quote) values ('有些事不用在一晚内做完的，我们又不赶时间，可以每晚都做一做');
insert into api.love_quotes(quote) values ('我发现昨天很喜欢你，今天也很喜欢你，而且有预感明天也会喜欢你。');
insert into api.love_quotes(quote) values ('跟你说一个坏消息 什么坏消息 我对你的思想已经不单纯了');
insert into api.love_quotes(quote) values ('不思进取，思你');
insert into api.love_quotes(quote) values ('既然你把我的心已经弄乱了，那你打算什么时候来弄乱我的床？');
insert into api.love_quotes(quote) values ('我已经规划好你的新身份了，那就是老婆大人。');
insert into api.love_quotes(quote) values ('喜欢你就是见不得你与别人交谈甚欢。');
insert into api.love_quotes(quote) values ('如果说最奢侈的事，我愿用我整个青春去等你');
insert into api.love_quotes(quote) values ('“你会看手相吗?”“会一点，你命里缺我”');
insert into api.love_quotes(quote) values ('我爱你，就会爱你的一切。');
insert into api.love_quotes(quote) values ('愿意跟我体验一下不单身的感觉吗。');
insert into api.love_quotes(quote) values ('“先生你要点什么？”“我想点开你的心。”');
insert into api.love_quotes(quote) values ('最好的时光里有了你，才能成为我所谓的最好的时光。');
insert into api.love_quotes(quote) values ('“我觉得你长得像我一个亲戚。”“？？？”“我妈的儿媳妇。”');
insert into api.love_quotes(quote) values ('“你知道情人眼里出什么吗？”“西施啊。”“不，出现你。”');
insert into api.love_quotes(quote) values ('最近有谣言说我喜欢你，我要澄清一下，那不是谣言。');
insert into api.love_quotes(quote) values ('“你知道我为什么感冒了吗?”“因为着凉了?”“不，因为我对你完全没有抵抗力。”');
insert into api.love_quotes(quote) values ('迩是莪一辈子旳宝贝。');
insert into api.love_quotes(quote) values ('爱你如初是假的，因为我一天比一天更爱你。');
insert into api.love_quotes(quote) values ('“我在找一条路”“春熙路？”“不是，阿姨洗铁路。”（日语我爱你的意思）');
insert into api.love_quotes(quote) values ('三十晚上的鞭炮再响，都没有我想想你那么想。');
insert into api.love_quotes(quote) values ('如果我丢了怎么办? 报警就好了 什么?');
insert into api.love_quotes(quote) values ('愿你为我你穿上婚纱，我陪你笑傲天下。');
insert into api.love_quotes(quote) values ('“如果人也有尾巴的话，这么说还真有点难为情呢。因为和你在一起的时候，我想，我会忍不住摇尾巴。”');
insert into api.love_quotes(quote) values ('“你可以笑一个吗？”“为什么啊？”“因为我的咖啡忘加糖了。”');
insert into api.love_quotes(quote) values ('你知道我最爱的是什么吗？现在看这句话第一个字就知道了');
insert into api.love_quotes(quote) values ('我想吃碗面 什么面 你的心里面。');
insert into api.love_quotes(quote) values ('我发现昨天很喜欢你，今天也很喜欢你，而且有预感明天也会喜欢你');
insert into api.love_quotes(quote) values ('我是九你是三，除了你还是你。');
insert into api.love_quotes(quote) values ('你知道墙壁，眼睛，膝盖的英文怎么说么? wall,eye,knee 我也是，我爱你。');
insert into api.love_quotes(quote) values ('我觉得你接近我就是在害我，害得我好喜欢你呀');
insert into api.love_quotes(quote) values ('吃烧烤是先考海鲜还是烤肉 烤肉 先考虑你');
insert into api.love_quotes(quote) values ('你的心，是我去到世界尽头还想再回来的地方。');
insert into api.love_quotes(quote) values ('我唯一没有做好的事，就是说了“我爱你”。');
insert into api.love_quotes(quote) values ('“既然你把我的心已经弄乱了，那你打算什么时候来弄乱我的床?”');
insert into api.love_quotes(quote) values ('我想买一块地…你的死心塌地');
insert into api.love_quotes(quote) values ('“面对你，我不仅善解人意，我还善解人衣。”');
insert into api.love_quotes(quote) values ('你若一直在，我便一直爱。');
insert into api.love_quotes(quote) values ('最近手头有点紧，想借你的手牵一牵');
insert into api.love_quotes(quote) values ('前半生到处浪荡，后半身为你煲汤');
insert into api.love_quotes(quote) values ('其实我有超能力，超级喜欢你');
insert into api.love_quotes(quote) values ('“n 55lw !n');
insert into api.love_quotes(quote) values ('对你最初的印象，久久难以忘怀。');
insert into api.love_quotes(quote) values ('人总是会变的，从一开始的喜欢你，到后来的更喜欢你');
insert into api.love_quotes(quote) values ('“你是不是喜欢我?”找出这句话中重复的字。');
insert into api.love_quotes(quote) values ('你是我的梦想	，以梦开始	，以想终止');
insert into api.love_quotes(quote) values ('猜猜我的心在哪边?左边。错了，在你那边。');
insert into api.love_quotes(quote) values ('你不爱我没事，让我心疼你。');
insert into api.love_quotes(quote) values ('“请管好你的嘴。”“为什么？”“因为我随时会亲它。”');
insert into api.love_quotes(quote) values ('我用尽了全部的运气，只为遇到你的那个瞬间，生命在那刻点亮。');
insert into api.love_quotes(quote) values ('万千人之中我也能一眼便认出你，因为别人走在路上，你走在我心上～');
insert into api.love_quotes(quote) values ('你过来 我有个天想跟你聊一下');
insert into api.love_quotes(quote) values ('甜有100种方式，吃糖，蛋糕，还有每天98次的想你');
insert into api.love_quotes(quote) values ('我只是爱你，没说非要在一起。');
insert into api.love_quotes(quote) values ('我不喜欢等，我只喜欢你。');
insert into api.love_quotes(quote) values ('每日每夜都想你，每时每刻都恋你，一生一世只爱你。');
insert into api.love_quotes(quote) values ('“你想养狗吗？”“什么狗？”“单身的那种”');
insert into api.love_quotes(quote) values ('别让我看见你，不然我见你一次，就喜欢你一次。');
insert into api.love_quotes(quote) values ('女孩，我十拿九稳 只差你一吻。');
insert into api.love_quotes(quote) values ('“我觉得你这个人不适合谈恋爱” “为什么?” “适合结婚。”');
insert into api.love_quotes(quote) values ('我们不再适合谈恋爱了，我们更适合结婚了。');
insert into api.love_quotes(quote) values ('你忙归忙，什么时候有空嫁给我？');
insert into api.love_quotes(quote) values ('知道我和唐僧什么区别吗？唐僧取经我娶你');
insert into api.love_quotes(quote) values ('你会喜欢我吗？不会我教你啊');
insert into api.love_quotes(quote) values ('跟你捉迷藏的话我肯定输，因为爱你的心怎么也藏不住');
insert into api.love_quotes(quote) values ('我喜欢你超过来两分钟了，不可以撤回了。');
insert into api.love_quotes(quote) values ('我本已百毒不侵，偏偏你是第101种，而且无药可解。');
insert into api.love_quotes(quote) values ('有了你，黑暗不再是黑暗');
insert into api.love_quotes(quote) values ('心在你那里，疼不疼你说了算。');
insert into api.love_quotes(quote) values ('咱们应当在一起，否则就太伤天害理啦。');
insert into api.love_quotes(quote) values ('情书是我抄的但我愛你是真的');
insert into api.love_quotes(quote) values ('没什么特别的事，只想听听你的声音。');
insert into api.love_quotes(quote) values ('因为知道不能没有你，所以我会更珍惜。');
insert into api.love_quotes(quote) values ('只有70件事最令我开心，一件是你，一件是69');
insert into api.love_quotes(quote) values ('你知道你像什么人吗?(什么人?)我的女人。');